### ISSUE TITLE
Using the android7.0 version, nubo-test cannot call the camera and display the black screen！

### ISSUE THREAD

**Issue by huanghm603** [nubomedia-vtt/nubo-test#11]
Using the android7.0 version, nubo-test cannot call the camera and display the black screen！

**Comment by huanghm603** [comment]
I have  solve this  problem：
PeerVideoActivity:
   private static final int REQUEST_EXTERNAL_STORAGE = 1;
    private static String[] PERMISSIONS_STORAGE = {
            "android.permission.READ_EXTERNAL_STORAGE",
            "android.permission.WRITE_EXTERNAL_STORAGE",
            "android.permission.CAMERA"};
    private static String[] CAMERA_PERMISSIONS_STORAGE = {
            "android.permission.CAMERA",
            "android.permission.MODIFY_AUDIO_SETTINGS",
            "android.permission.RECORD_AUDIO",
            "android.permission.CAPTURE_VIDEO_OUTPUT"};

    public static void verifyStoragePermissions(Activity activity) {

        try {
            //检测是否有写的权限
            int permission = ActivityCompat.checkSelfPermission(activity,"android.permission.WRITE_EXTERNAL_STORAGE");
            if (permission != PackageManager.PERMISSION_GRANTED) {
                // 没有写的权限，去申请写的权限，会弹出对话框
                ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,REQUEST_EXTERNAL_STORAGE);
            }
            permission = ActivityCompat.checkSelfPermission(activity,"android.permission.CAMERA");
            if (permission != PackageManager.PERMISSION_GRANTED) {
                ActivityCompat.requestPermissions(activity, CAMERA_PERMISSIONS_STORAGE,REQUEST_EXTERNAL_STORAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
onCreate(){
//添加权限
   verifyStoragePermissions(PeerVideoActivity.this);
}

**Comment by Lyoona** [comment]
您好，我也遇见了同样的问题，我的手机端可以获取web端的音视频流，但是好像手机端的没有传给web，我已经添加了权限，请问，您是怎么解决这个问题的？

**Comment by huanghm603** [comment]
我上面说了解决方案了，你把上面的代码添加进去就可以了。主要是手机端没有获得摄像头和音频权限。

**Comment by Lyoona** [comment]
您好，我已经按照您上述代码加入了，动态申请了权限，但是还是没能拿到本地的音视频流，请问，除了上面这里，您还改了哪些地方吗？

**Comment by huanghm603** [comment]
动态申请后，在onCreate(),加入该方法，即可，其他的没有更改。

**Comment by Lyoona** [comment]
我在试试，方便留个联系方式，讨论一下吗？

**Comment by MrsZ** [comment]
你们解决了吗？我加了也不行 哈哈 求方法呀
