### ISSUE TITLE
Can you provide a multiplayer chat version?

### ISSUE THREAD

**Issue by lchben** [nubomedia-vtt/nubo-test#3]
Ios demo seems to improve a lot.Android demo too simple!

**Comment by jpsjanne** [comment]
Hi, nubo-test is a simple demonstration, test, and validation software for the Android client API. It provides a good template for working on your own project but is not really an end-user product. If you think that there is something missing from the API itself then I will take it into consideration.

But out of curiosity, what is it exactly that you would like to see in nubo-test? There is already a room chat present where everyone in the same room can chat with everyone.

**Comment by lchben** [comment]
@jpsjanne  Thank you for your answer. Thank you

**Comment by jpsjanne** [comment]
You're welcome...

**Comment by sushantNoida** [comment]
Right now. It's one2one video chat. I request  you to add many many( group call) in Android.
