### ISSUE TITLE
When more than twos person joins the room，One of them  Always ‘show waiting_remote_stream’

### ISSUE THREAD

**Issue by lchben** [nubomedia-vtt/nubo-test#5]
Three person  join the room.One of them will not hear or send a voice

**Comment by lchben** [comment]
I joined in a room and then quit. When I was joined the room again, the people in the room didn't hear my voice.them Always ‘show waiting_remote_stream’

**Comment by lchben** [comment]
@jpsjanne Maybe you can help me to answer this question? I need your help

**Comment by lchben** [comment]
@jpsjanne  I have solved this problem.The reason for this problem is：Someone left the room, but you did not close the connection with him.When he entered the room again, you did not create his steam 
![image](https://cloud.githubusercontent.com/assets/12679661/20957909/9d21ccd8-bc8d-11e6-9cb5-41f588fe75c1.png)

Solution：

![image](https://cloud.githubusercontent.com/assets/12679661/20957814/0136f51e-bc8d-11e6-9787-42fd50870bfc.png)
![image](https://cloud.githubusercontent.com/assets/12679661/20957820/0db8013e-bc8d-11e6-9c3c-3010bcee3a15.png)

But this method may not be the best.Maybe you have a good way.

**Comment by jpsjanne** [comment]
Hi, thanks for pointing out this bug! Your approach is correct, and I will commit this fix on nubo-test.

**Comment by lchben** [comment]
@jpsjanne  I also found a problem: I added a methodto control the sound
![image](https://cloud.githubusercontent.com/assets/12679661/20995500/78294064-bd32-11e6-876b-185ae0ddf97a.png)
When a person exits the room . I performed a close of his connection  
![image](https://cloud.githubusercontent.com/assets/12679661/20995563/da73f246-bd32-11e6-8707-97953525ae33.png)
Then I execute the control sound method .app will crash.
![image](https://cloud.githubusercontent.com/assets/12679661/20995720/d4e5b9f8-bd33-11e6-9018-81b14c71d861.png)

I thought it was because I closed his connection, but his stream was still there.When I operated this method of controlling the sound, the crash occurred.But I do not know how to delete his stream. I did not find this method

**Comment by jpsjanne** [comment]
Have you tried removing the executor.execute block? I don't think it's necessary for this process. I have to admit that it's used too much in this project in general.

**Comment by lchben** [comment]
@jpsjanne  I have solved this problem：When a person leaves the room,  needs to stop receiving his video
![image](https://cloud.githubusercontent.com/assets/12679661/21071469/f6ac4666-bedb-11e6-93e3-1e4559c62303.png)
